services:
  web:
    build: .
    container_name: odoo-catering
    command: ["odoo", "--config", "/etc/odoo/odoo.conf"]
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_password
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./volumes/odoo-web-data:/var/lib/odoo
    restart: unless-stopped
    networks:
      - odoo-network

  db:
    image: postgres:15
    container_name: odoo-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - odoo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: odoo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
